### ISSUE TITLE
train-face-detector dataset not found

### ISSUE THREAD

**Issue by paulinder** [torch/demos#19]
I tried running the face detector demo, but was unable to download the dataset.

Using ```wget http://data.neuflow.org/data/faces_cut_yuv_32x32.tar.gz``` I'm getting a ```403 Forbidden```, and using ```https://engineering.purdue.edu/elab/files/face-dataset.zip``` I'm getting a ```404 Not Found```. 

I tried to find the files via web search, but couldn't get a working link.

**Comment by soumith** [comment]
should be fixed now, thanks to @Atcold

**Comment by paulinder** [comment]
Thanks to you both.

**Comment by Atcold** [comment]
@paulinder, your welcome.

**Comment by rickerliang** [comment]
The dataset download failed again, please fix it.

**Comment by Atcold** [comment]
Again???
@culurciello, did you take down the content, by any chance?
