### ISSUE TITLE
person-detector: dataset URL is broken

### ISSUE THREAD

**Issue by erosennin** [torch/demos#20]
The `person-detector` demo tries to fetch the dataset from a nonexistent URL:

```
$ wget https://engineering.purdue.edu/elab/files/INRIAPerson.zip
--2015-05-20 16:05:01--  https://engineering.purdue.edu/elab/files/INRIAPerson.zip
Resolving engineering.purdue.edu (engineering.purdue.edu)... 128.46.104.5
Connecting to engineering.purdue.edu (engineering.purdue.edu)|128.46.104.5|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
```

**Comment by soumith** [comment]
@Aysegul @Atcold @jhjin what happend to the dataaaaaa?

**Comment by Atcold** [comment]
*Someone* may have used `rm -rf`...
I'm calling the IT department for accessing the backups.

I apologise :neutral_face:

**Comment by Atcold** [comment]
Done. Please close the issue.

**Comment by soumith** [comment]
hehe, thanks alfredo.

**Comment by Atcold** [comment]
@soumith, np. The funny-sad part is that I don't even get to get angry to who did this :rage:
