### ISSUE TITLE
Demo Data Pre-Processing Process

### ISSUE THREAD

**Issue by woffle** [torch/demos#29]
Could we please explain the pre-processing done on the datasets that are downloaded from the AWS servers? In particular the MNIST and CIFAR datasets. Would be useful to train a model and be able to test it on new 'unseen' data.

**Comment by soumith** [comment]
The datasets download from AWS servers dont have any pre-processing done (as far as I know). The images were loaded via image.load (into a floating point range of [0, 1] ). The rest of the pre-processing such as mean-subtraction etc. is handled in the training scripts themselves. Just make sure that's the case by printing out the :mean() and :std() of the datasets.
