### ISSUE TITLE
CUDA version of the train-on-cifar.lua

### ISSUE THREAD

**Issue by srp1970** [torch/demos#30]
Do we have CUDA version for this train-on-cifar.lua? I did the following:

1. Change as follows:
-- load dataset
torch.setdefaulttensortype("torch.CudaTensor")
trainData = {
   data = torch.CudaTensor(50000, 3072), <== changed from torch.Tensor
   labels = torch.CudaTensor(50000),

2. Similar changes for "mlp" model case too.

But it gives the error saying:

<trainer> preprocessing data (color space + normalization)
/usr6/prakash/DNN/Torch/luajit-rocks/bin/luajit: invalid arguments: number number
expected arguments: *CudaTensor* [float] [float]
stack traceback:
        [C]: at 0x7f2bb2949010
        [C]: in function 'uniform'
        .../luajit-rocks/share/lua/5.1/nn/SpatialConvolutionMap.lua:103: in function 'reset'
        .../luajit-rocks/share/lua/5.1/nn/SpatialConvolutionMap.lua:73: in function '__init'
        ...kash/DNN/Torch/luajit-rocks/share/lua/5.1/torch/init.lua:54: in function <...kash/DNN/Torch/luajit-rocks/share/lua/5.1/torch/init.lua:50>
        [C]: in function 'SpatialConvolutionMap'
        ...cks/share/lua/5.1/nn/SpatialSubtractiveNormalization.lua:35: in function '__init'
        ...kash/DNN/Torch/luajit-rocks/share/lua/5.1/torch/init.lua:54: in function <...kash/DNN/Torch/luajit-rocks/share/lua/5.1/torch/init.lua:50>
        [C]: in function 'SpatialSubtractiveNormalization'
        ...cks/share/lua/5.1/nn/SpatialContrastiveNormalization.lua:23: in function '__init'
        ...kash/DNN/Torch/luajit-rocks/share/lua/5.1/torch/init.lua:54: in function <...kash/DNN/Torch/luajit-rocks/share/lua/5.1/torch/init.lua:50>
        [C]: in function 'SpatialContrastiveNormalization'
        train-on-cifar-cuda.lua:187: in main chunk
        [C]: in function 'dofile'
        ...Torch/luajit-rocks/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x004051e0

**Comment by soumith** [comment]
have a look at https://github.com/szagoruyko/cifar.torch as well as a blog post here:
torch.ch/blog/2015/07/30/cifar.html
