### ISSUE TITLE
 bad argument #2 to '?' (out of range at at /home/dazhen/torch/pkg/torch/generic/Tensor.c:853)

### ISSUE THREAD

**Issue by dazhenseu** [torch/demos#36]
hi~I ran the demo train-a-digit-classifier, and found when I set the batchsize more bigger,like 300, the procedure occured an error of out of range. 
Actually, I also noticed the torch/optim project is updated for some simlar errors, but after I updated the optim page using "luarocks install optim", it still didn't work.
So, how can I fix this problem for big batchsize.By the way, I am kind of confusion about the ConfusionMatrix;what's the effect of the matrix?

**Comment by karandwivedi42** [comment]
How did you solve this?
